import type { Metadata } from "next";
import { Exo} from "next/font/google";
import "./globals.css";
import {NavigationMenuDemo} from "./_components/navbar/navbar"
import { Toaster } from "@/components/ui/sonner"

import WrapperComp from "./_components/wrapperComp";
import TanstackProviders from "@/providers/TanstackProvider";
const exo = Exo({
  subsets: ["latin"],
  weight:['500','600']
});



export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={exo.className}
    >
      <head>
         <link rel="icon" href="/freshcart-logo.49f1b44d.svg" type="image/svg+xml" />

      </head>
      <body className=" flex flex-col">
       <TanstackProviders>
          {/* navbar */}
          <WrapperComp>
            <NavigationMenuDemo/>
          </WrapperComp>
       
        
      
        <div className="container max-w-350 mx-auto py-5">
          
           {children}
        </div>
         <Toaster/>
       </TanstackProviders>
       
      </body>

    </html>
  );
}
